kind: config
providers:
  grafana:
    kind: grafana
    endpoint: https://alerting-grafana.sonic-us.supersonicads.com
    token: eyJrIjoiQVZLaDFwZmk1bXVhOEc4WTBDMmNGd1JOTGhWV0t6a3oiLCJuIjoiZ2RidCIsImlkIjoxfQ==
  vmdb:
    kind: prometheus
    endpoint: http://vmdb.sonic-us.supersonicads.com:8248
  consul:
    kind: consul
    endpoint: http://consul1.sonic-us.us-east-1.ec2ssa.info:8500
    path: gdbt/state
state: consul
evaluations:
  aerospike:
    kind: prometheus
    source: vmdb
    metric: "avg(prometheus_aerospike_namespace_memory_free_pct) by (aerospike_cluster)"
    label: "aerospike_cluster"
# lookups:
#   hello: world
#   foo:
#     bar: 1
#     baz: 2
